INSERT INTO staging.hh_vacancies (
    vacancy_id,
    fetched_at,
    area_id,
    area_name,
    area_url,
    code,
    name,
    test,
    type_id,
    type_name,
    hidden,
    salary_from,
    salary_to,
    salary_currency,
    salary_gross,
    address,
    premium,
    approved,
    archived,
    contacts,
    employer_id,
    employer_url,
    employer_name,
    employer_trusted,
    employer_logo_urls,
    employer_country_id,
    employer_alternate_url,
    employer_vacancies_url,
    employer_is_identified_by_esia,
    employer_accredited_it,
    has_test,
    schedule_id,
    schedule_name,
    languages,
    relations,
    created_at,
    department,
    employment_id,
    employment_name,
    experience_id,
    experience_name,
    internship,
    key_skills,
    accept_kids,
    description,
    work_format,
    night_shifts,
    published_at,
    response_url,
    salary_range_from,
    salary_range_to,
    salary_range_currency,
    salary_range_gross,
    salary_range_mode_id,
    salary_range_mode_name,
    salary_range_frequency_id,
    salary_range_frequency_name,
    working_days,
    alternate_url,
    show_contacts,
    working_hours,
    allow_messages,
    age_restriction,
    specializations,
    accept_temporary,
    negotiations_url,
    insider_interview,
    accept_handicapped,
    initial_created_at,
    professional_roles,
    working_time_modes,
    apply_alternate_url,
    branded_description,
    driver_license_types,
    closed_for_applicants,
    work_schedule_by_days,
    working_time_intervals,
    fly_in_fly_out_duration,
    response_letter_required,
    accept_incomplete_resumes,
    vacancy_constructor_template
)
SELECT
    (payload->>'id')::bigint,
    fetched_at,
    (payload->'area'->>'id')::bigint,
    payload->'area'->>'name',
    payload->'area'->>'url',
    payload->>'code',
    payload->>'name',
    payload->>'test',
    payload->'type'->>'id',
    payload->'type'->>'name',
    (payload->>'hidden')::boolean,
    (payload->'salary'->>'from')::int,
    (payload->'salary'->>'to')::int,
    payload->'salary'->>'currency',
    (payload->'salary'->>'gross')::boolean,
    payload->'address',
    (payload->>'premium')::boolean,
    (payload->>'approved')::boolean,
    (payload->>'archived')::boolean,
    payload->>'contacts',
    (payload->'employer'->>'id')::bigint,
    payload->'employer'->>'url',
    payload->'employer'->>'name',
    (payload->'employer'->>'trusted')::boolean,
    payload->'employer'->'logo_urls',
    (payload->'employer'->>'country_id')::int,
    payload->'employer'->>'alternate_url',
    payload->'employer'->>'vacancies_url',
    (payload->'employer'->>'is_identified_by_esia')::boolean,
    (payload->'employer'->>'accredited_it_employer')::boolean,
    (payload->>'has_test')::boolean,
    payload->'schedule'->>'id',
    payload->'schedule'->>'name',
    payload->'languages',
    payload->'relations',
    (payload->>'created_at')::timestamptz,
    payload->>'department',
    payload->'employment'->>'id',
    payload->'employment'->>'name',
    payload->'experience'->>'id',
    payload->'experience'->>'name',
    (payload->>'internship')::boolean,
    payload->'key_skills',
    (payload->>'accept_kids')::boolean,
    payload->>'description',
    payload->'work_format',
    (payload->>'night_shifts')::boolean,
    (payload->>'published_at')::timestamptz,
    payload->>'response_url',
    (payload->'salary_range'->>'from')::int,
    (payload->'salary_range'->>'to')::int,
    payload->'salary_range'->>'currency',
    (payload->'salary_range'->>'gross')::boolean,
    payload->'salary_range'->'mode'->>'id',
    payload->'salary_range'->'mode'->>'name',
    payload->'salary_range'->'frequency'->>'id',
    payload->'salary_range'->'frequency'->>'name',
    payload->'working_days',
    payload->>'alternate_url',
    (payload->>'show_contacts')::boolean,
    payload->'working_hours',
    (payload->>'allow_messages')::boolean,
    payload->>'age_restriction',
    payload->'specializations',
    (payload->>'accept_temporary')::boolean,
    payload->>'negotiations_url',
    payload->>'insider_interview',
    (payload->>'accept_handicapped')::boolean,
    (payload->>'initial_created_at')::timestamptz,
    payload->'professional_roles',
    payload->'working_time_modes',
    payload->>'apply_alternate_url',
    payload->>'branded_description',
    payload->'driver_license_types',
    (payload->>'closed_for_applicants')::boolean,
    payload->'work_schedule_by_days',
    payload->'working_time_intervals',
    payload->'fly_in_fly_out_duration',
    (payload->>'response_letter_required')::boolean,
    (payload->>'accept_incomplete_resumes')::boolean,
    payload->>'vacancy_constructor_template'
FROM raw.hh_vacancies
WHERE payload IS NOT NULL
AND payload <> '{}'
AND (payload->>'id')::bigint = ANY(%s)
ON CONFLICT (vacancy_id) DO UPDATE
SET
    fetched_at = EXCLUDED.fetched_at,
    area_id = EXCLUDED.area_id,
    area_name = EXCLUDED.area_name,
    area_url = EXCLUDED.area_url,
    code = EXCLUDED.code,
    name = EXCLUDED.name,
    test = EXCLUDED.test,
    type_id = EXCLUDED.type_id,
    type_name = EXCLUDED.type_name,
    hidden = EXCLUDED.hidden,
    salary_from = EXCLUDED.salary_from,
    salary_to = EXCLUDED.salary_to,
    salary_currency = EXCLUDED.salary_currency,
    salary_gross = EXCLUDED.salary_gross,
    address = EXCLUDED.address,
    premium = EXCLUDED.premium,
    approved = EXCLUDED.approved,
    archived = EXCLUDED.archived,
    contacts = EXCLUDED.contacts,
    employer_id = EXCLUDED.employer_id,
    employer_url = EXCLUDED.employer_url,
    employer_name = EXCLUDED.employer_name,
    employer_trusted = EXCLUDED.employer_trusted,
    employer_logo_urls = EXCLUDED.employer_logo_urls,
    employer_country_id = EXCLUDED.employer_country_id,
    employer_alternate_url = EXCLUDED.employer_alternate_url,
    employer_vacancies_url = EXCLUDED.employer_vacancies_url,
    employer_is_identified_by_esia = EXCLUDED.employer_is_identified_by_esia,
    employer_accredited_it = EXCLUDED.employer_accredited_it,
    has_test = EXCLUDED.has_test,
    schedule_id = EXCLUDED.schedule_id,
    schedule_name = EXCLUDED.schedule_name,
    languages = EXCLUDED.languages,
    relations = EXCLUDED.relations,
    created_at = EXCLUDED.created_at,
    department = EXCLUDED.department,
    employment_id = EXCLUDED.employment_id,
    employment_name = EXCLUDED.employment_name,
    experience_id = EXCLUDED.experience_id,
    experience_name = EXCLUDED.experience_name,
    internship = EXCLUDED.internship,
    key_skills = EXCLUDED.key_skills,
    accept_kids = EXCLUDED.accept_kids,
    description = EXCLUDED.description,
    work_format = EXCLUDED.work_format,
    night_shifts = EXCLUDED.night_shifts,
    published_at = EXCLUDED.published_at,
    response_url = EXCLUDED.response_url,
    salary_range_from = EXCLUDED.salary_range_from,
    salary_range_to = EXCLUDED.salary_range_to,
    salary_range_currency = EXCLUDED.salary_range_currency,
    salary_range_gross = EXCLUDED.salary_range_gross,
    salary_range_mode_id = EXCLUDED.salary_range_mode_id,
    salary_range_mode_name = EXCLUDED.salary_range_mode_name,
    salary_range_frequency_id = EXCLUDED.salary_range_frequency_id,
    salary_range_frequency_name = EXCLUDED.salary_range_frequency_name,
    working_days = EXCLUDED.working_days,
    alternate_url = EXCLUDED.alternate_url,
    show_contacts = EXCLUDED.show_contacts,
    working_hours = EXCLUDED.working_hours,
    allow_messages = EXCLUDED.allow_messages,
    age_restriction = EXCLUDED.age_restriction,
    specializations = EXCLUDED.specializations,
    accept_temporary = EXCLUDED.accept_temporary,
    negotiations_url = EXCLUDED.negotiations_url,
    insider_interview = EXCLUDED.insider_interview,
    accept_handicapped = EXCLUDED.accept_handicapped,
    professional_roles = EXCLUDED.professional_roles,
    working_time_modes = EXCLUDED.working_time_modes,
    apply_alternate_url = EXCLUDED.apply_alternate_url,
    branded_description = EXCLUDED.branded_description,
    driver_license_types = EXCLUDED.driver_license_types,
    closed_for_applicants = EXCLUDED.closed_for_applicants,
    work_schedule_by_days = EXCLUDED.work_schedule_by_days,
    working_time_intervals = EXCLUDED.working_time_intervals,
    fly_in_fly_out_duration = EXCLUDED.fly_in_fly_out_duration,
    response_letter_required = EXCLUDED.response_letter_required,
    accept_incomplete_resumes = EXCLUDED.accept_incomplete_resumes,
    vacancy_constructor_template = EXCLUDED.vacancy_constructor_template;